### ISSUE TITLE
Add chat reminder on how to fix rope rendering

### ISSUE THREAD

**Issue by NotPaddy** [ScrewdriverHyena/ParkourFortress-Bugs#1]
Something something FPS configs breaking shit.
Use:
r_drawropes 1
rope_rendersolid 1

**Comment by itVictor** [comment]
Just want to point out that just those two commands won't fix ropes not appearing for everyone if you're using a fps config, the results seem to vary from user to user.

For example, I had to adjust the values for r_queued_ropes and rope_averagelight (in addition to r_drawropes and rope_rendersolid) in order to make ropes actually appear, but the ones you mentioned are definitely the main ones peope will need to mess with.

**Comment by namishere** [comment]
Very basic implementation has been added, can be improved

**Comment by ScrewdriverHyena** [comment]
Issue #1 finally eliminated in commit 886da19 (server repo)
