### ISSUE TITLE
Wallrun Range Being shorter than on slag

### ISSUE THREAD

**Issue by ratlasob** [ScrewdriverHyena/ParkourFortress-Bugs#56]
The current max telewallrun range is I believe 244 units.  On slag it was at least 256, but i suspect it was actually even a notable amount longer than that.

**Comment by ScrewdriverHyena** [comment]
Despite being an inconsistency with the original, I don't see us extending telewallrun range to the lengths of the original, (from accounts I also recall it was definitely greater than 256, but while looking for it I can't find any source for that. The figure I remember is 350 units.) mostly because it doesn't make sense to magically teleport to a wall which is far away from the player and start wallrunning. For edge cases like the barely-possible wallrun on underground, I'll possibly talk to the map author about whether he would like to either make it easier or remove the shortcut altogether.

I will keep this issue open in case there's any other particular reason why this needs to be changed, but for now I'll also go ahead and mark this as "wont-fix"

**Comment by ScrewdriverHyena** [comment]
No responses to the request for comment in over 2 months, so I'm going to go ahead and close this one.
