### ISSUE TITLE
Not regenerating health after damage triggers

### ISSUE THREAD

**Issue by ratlasob** [ScrewdriverHyena/ParkourFortress-Bugs#61]
Most easily seen on mizuki, after taking damage from the water, no health is regenerated.  Should you take fall damage and are still missing health while taking the water damage, health is regenerated properly.  If fall damage is taken after the water damage, health is regenerated properly.

**Comment by ScrewdriverHyena** [comment]
The health regeneration system has been problematic since the start due to how it's written (Currently it uses a timer followed by a repeating timer, and I believe having multiple players regenerating can break it)

I think there's a way to fix this by using a native method of health regen in TF2; possibly attributes.

**Comment by ScrewdriverHyena** [comment]
This was fixed with the recent damage changes.

The issue was that damage marked as "drowning" damage was being thrown out rather than regenerated. This is no longer the case.
