### ISSUE TITLE
Bug with TOONHUD

### ISSUE THREAD

**Issue by EmiChanTF2** [ScrewdriverHyena/ParkourFortress-Bugs#71]
Basically, whenever i use Toonhud on here this happens.
![image](https://user-images.githubusercontent.com/57962814/69178048-b9015800-0b00-11ea-9667-9aa6f178e84a.png)

**Comment by Magnanix** [comment]
Hey there, thanks for the report. This is known as another user has encountered it, some of our staff use ToonHUD as well, and the problem is local. Please refer to this image for help, notify us if it does not solve the problem!
![ss+(2019-11-19+at+06 37 14)](https://user-images.githubusercontent.com/20764341/69196231-daac1080-0afb-11ea-9e1c-041fd0f52b2c.png)

**Comment by EmiChanTF2** [comment]
yeah, that's...me. and it's still not fixed. it was nothing to do with transparent vms cause im not using them anymore.

**Comment by defenitlynotironicedgyboy** [comment]
i got it too on all of my screen once
