### ISSUE TITLE
Wallrun jump bug

### ISSUE THREAD

**Issue by shuk-fuk** [ScrewdriverHyena/ParkourFortress-Bugs#81]
https://youtu.be/ARwjiaxCJoo

instantly jumping out of a wallrun can cause you to get "stuck"

this only happens when using mousewheel which means it must be caused by inputting a wallrun + wallrun jump too fast

**Comment by Magnanix** [comment]
Looking over the video, you managed to detach yourself from the wallrun as it started. That moment when traveling at 319 units is actually you rubbing up against the wall having slammed into it at 460 units from a bunnyhop, and not inside a wallrun action.

This can be worked on, to reduce the input acceptance of jump by a microsecond, however this is maxmin-ing the controls and is not representative of what Parkour.TF is intending by using the scroll wheel to jump rather than the spacebar.

**Comment by shuk-fuk** [comment]
...that last comment was kind of unnecessary. it's not like im running scripts and using an auto strafer or whatever. THAT would be minmaxing. im simply using mousewheel so i dont have to mash 6 keys at once if i want to get off from a wall faster. it's comfortable optimizing that has been used since early slag days. i dont understand your denial of parkour being a speed game when it's clearly fit to be one.

**Comment by Magnanix** [comment]
To initiate a wallrun, +Forward, with +Left or +Right, with +Jump in that order. Three controls. To release yourself from the wall attachment, +Jump or +Crouch. Two options for different effects. Total coming to 4 (four) key actuations for the effect you are requesting.

The use of scroll wheel, scripts, or loops spams +Jump into the system and will cause unintended interactions, such as the present topic. There is no denial that Parkour.TF is presenting a gamemode about speed and optimization, however our controls are more complex for such simple actions. By changing our default control, you open yourself to not intended gameplay, which is fine though we can only adjust what doesn't effect the baseline player experience to "fix" the top end.

Any further conversation deviating from the bug report will result in an automatic close.

**Comment by ScrewdriverHyena** [comment]
I will be taking a look soon

**Comment by ScrewdriverHyena** [comment]
Fixed in previous bug patch.
