### ISSUE TITLE
long jumps require +forward to be held

### ISSUE THREAD

**Issue by shuk-fuk** [ScrewdriverHyena/ParkourFortress-Bugs#89]
makes it harder to strafe after a long jump. unless you're a dirty w strafer...

**Comment by ScrewdriverHyena** [comment]
`if (iButtons & IN_ATTACK2 && CPFSpeedController.GetBoost(iClient) && CPFSpeedController.GetSpeed(iClient) == SPEED_MAX_BOOST && IsOnGround(iClient))
    CPFLongjumpHandler.Longjump(iClient);`
So, as is, we don't _directly_ require forward held to longjump, that can be ruled out.

I do believe I may know the issue here, however. It could be due to requiring boost for longjump, and the boost only being triggered while running.

**Comment by ScrewdriverHyena** [comment]
Fixed in commit e7af57
